# Generated by Django 4.2.4 on 2025-09-18 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_order_description_order_delivery_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='four_trips',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='three_trips',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='two_trips',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_time',
        ),
        migrations.AddField(
            model_name='customer',
            name='delivery_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customer',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
