# Generated by Django 4.2.4 on 2025-09-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_order_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gallons',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
