# Generated by Django 4.2.4 on 2025-09-24 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_customer_gallons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
